export const EMANATOR_HEADLINES = [
  "What wants to be built through you today?",
  "Let's give shape to something real.",
  "Follow the signal.",
  "Build what's asking to exist.",
  "Turn motion into form.",
  "The next version of this starts now.",
  "Shape the unseen into the inevitable.",
  "Your instinct knows the architecture.",
  "Begin where clarity meets courage.",
  "What would you build if nothing could fail?",
  "Trust the direction. Start building.",
  "Make the invisible visible.",
  "This is where intention becomes structure.",
  "The best code starts as a feeling.",
  "Something is ready to take form.",
  "Build like no one is watching.",
  "The signal is clear. Follow it.",
  "One prompt away from something real.",
  "Let the work reveal itself.",
  "Start with what moves you.",
  "Every great product began as a whisper.",
  "The blueprint is already inside you.",
  "Create what the world doesn't know it needs yet.",
  "From thought to thing. Let's go.",
]
